{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMMqQq+cicf7zKt8BjfEGGB"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":null,"metadata":{"id":"O3XZk8B2aFkL"},"outputs":[],"source":["import numpy as np\n","import pandas as pd\n","from sklearn import preprocessing\n","from sklearn.impute import KNNImputer, SimpleImputer\n","from sklearn.linear_model import LinearRegression, LogisticRegression\n","from sklearn.pipeline import make_pipeline\n","from sklearn.preprocessing import RobustScaler, StandardScaler, PolynomialFeatures\n","from sklearn.preprocessing import LabelEncoder, OneHotEncoder\n","from sklearn.decomposition import PCA\n","from scipy.stats import zscore"]},{"cell_type":"markdown","source":["<h1>DATA PREPROCESSING</h1>"],"metadata":{"id":"Ev_hEvv9kFyS"}},{"cell_type":"code","source":["#@title preprocessing_classes\n","class Duplicates:\n","    def __init__(self, duplicates=True):\n","        self.duplicates = duplicates\n","    def fit(self, X, y=None):\n","        return self\n","    def transform(self, X):\n","        return X\n","    def handle(self, df):\n","        if self.duplicates:\n","            original_shape = df.shape\n","            df.drop_duplicates(inplace=True, ignore_index=True)\n","            df.reset_index(drop=True, inplace=True)\n","            new_shape = df.shape\n","            count = original_shape[0] - new_shape[0]\n","        return df\n","\n","--*\n","class MissingValues:\n","    def __init__(self, missing_num=None, missing_categ=None):\n","        self.missing_num = missing_num\n","        self.missing_categ = missing_categ\n","    def fit(self, X, y=None):\n","        return self\n","    def transform(self, X):\n","        return X\n","    def handle(self, df, _n_neighbors=5):\n","        if self.missing_num or self.missing_categ:\n","            self.count_missing = df.isna().sum().sum()\n","            if self.count_missing != 0:\n","                df = df.dropna(how='all')\n","                df.reset_index(drop=True)\n","                if self.missing_num: # numeric data\n","                    if self.missing_num == 'auto':\n","                        self.missing_num = 'linreg'\n","                        lr = LinearRegression()\n","                        df = self._lin_regression_impute(df, lr)\n","                        self.missing_num = 'knn'\n","                        imputer = KNNImputer(n_neighbors=_n_neighbors)\n","                        df = self._impute(df, imputer, type='num')\n","                    elif self.missing_num in ['mean', 'median', 'most_frequent']:\n","                        imputer = SimpleImputer(strategy=self.missing_num)\n","                        df = self._impute(df, imputer, type='num')\n","                    elif self.missing_num == 'delete':\n","                        df = self._delete(df, type='num')\n","\n","                if self.missing_categ: # categorical data\n","                    if self.missing_categ == 'auto':\n","                        self.missing_categ = 'logreg'\n","                        lr = LogisticRegression()\n","                        df = self._log_regression_impute(df, lr)\n","                        self.missing_categ = 'knn'\n","                        imputer = KNNImputer(n_neighbors=_n_neighbors)\n","                        df = self._impute(df, imputer, type='categ')\n","                    elif self.missing_categ == 'most_frequent':\n","                        imputer = SimpleImputer(strategy=self.missing_categ)\n","                        df = self._impute(df, imputer, type='categ')\n","                    elif self.missing_categ == 'delete':\n","                        df = self._delete(df, type='categ')\n","            else:\n","                pass\n","        else:\n","            pass\n","        return df\n","    def _impute(self, df, imputer, type):\n","        cols_num = df.select_dtypes(include=np.number).columns\n","        if type == 'num':\n","            for feature in df.columns:\n","                if feature in cols_num:\n","                    if df[feature].isna().sum().sum() != 0:\n","                        try:\n","                            df_imputed = pd.DataFrame(imputer.fit_transform(np.array(df[feature]).reshape(-1, 1)))\n","                            counter = df[feature].isna().sum().sum() - df_imputed.isna().sum().sum()\n","\n","                            if (df[feature].fillna(-9999) % 1  == 0).all():\n","                                df[feature] = df_imputed\n","                                df[feature] = df[feature].round()\n","                                df[feature] = df[feature].astype('Int64')\n","                            else:\n","                                df[feature] = df_imputed\n","                            if counter != 0:\n","                                pass\n","                        except:\n","                            pass\n","        else:\n","            for feature in df.columns:\n","                if feature not in cols_num:\n","                    if df[feature].isna().sum()!= 0:\n","                        try:\n","                            mapping = dict()\n","                            mappings = {k: i for i, k in enumerate(df[feature].dropna().unique(), 0)}\n","                            mapping[feature] = mappings\n","                            df[feature] = df[feature].map(mapping[feature])\n","                            df_imputed = pd.DataFrame(imputer.fit_transform(np.array(df[feature]).reshape(-1, 1)), columns=[feature])\n","                            counter = sum(1 for i, j in zip(list(df_imputed[feature]), list(df[feature])) if i != j)\n","                            df[feature] = df_imputed\n","                            df[feature] = df[feature].round()\n","                            df[feature] = df[feature].astype('Int64')\n","                            mappings_inv = {v: k for k, v in mapping[feature].items()}\n","                            df[feature] = df[feature].map(mappings_inv)\n","                        except:\n","                            pass\n","        return df\n","    def _lin_regression_impute(self, df, model):\n","        cols_num = df.select_dtypes(include=np.number).columns\n","        mapping = dict()\n","        for feature in df.columns:\n","            if feature not in cols_num:\n","                mappings = {k: i for i, k in enumerate(df[feature])}\n","                mapping[feature] = mappings\n","                df[feature] = df[feature].map(mapping[feature])\n","        for feature in cols_num:\n","            try:\n","                test_df = df[df[feature].isnull()==True].dropna(subset=[x for x in df.columns if x != feature])\n","                train_df = df[df[feature].isnull()==False].dropna(subset=[x for x in df.columns if x != feature])\n","                if len(test_df.index) != 0:\n","                    pipe = make_pipeline(StandardScaler(), model)\n","                    y = np.log(train_df[feature])\n","                    X_train = train_df.drop(feature, axis=1)\n","                    test_df.drop(feature, axis=1, inplace=True)\n","                    try:\n","                        model = pipe.fit(X_train, y)\n","                    except:\n","                        y = train_df[feature]\n","                        model = pipe.fit(X_train, y)\n","                    if (y == train_df[feature]).all():\n","                        pred = model.predict(test_df)\n","                    else:\n","                        pred = np.exp(model.predict(test_df))\n","                    test_df[feature]= pred\n","                    if (df[feature].fillna(-9999) % 1  == 0).all():\n","                        test_df[feature] = test_df[feature].round()\n","                        test_df[feature] = test_df[feature].astype('Int64')\n","                        df[feature].update(test_df[feature])\n","                    else:\n","                        df[feature].update(test_df[feature])\n","            except:\n","                pass\n","        for feature in df.columns:\n","            try:\n","                mappings_inv = {v: k for k, v in mapping[feature].items()}\n","                df[feature] = df[feature].map(mappings_inv)\n","            except:\n","                pass\n","        return df\n","    def _log_regression_impute(self, df, model):\n","        cols_num = df.select_dtypes(include=np.number).columns\n","        mapping = dict()\n","        for feature in df.columns:\n","            if feature not in cols_num:\n","                mappings = {k: i for i, k in enumerate(df[feature])}\n","                mapping[feature] = mappings\n","                df[feature] = df[feature].map(mapping[feature])\n","        for feature in cols_num:\n","            try:\n","                test_df = df[df[feature].isnull()==True].dropna(subset=[x for x in df.columns if x != feature])\n","                train_df = df[df[feature].isnull()==False].dropna(subset=[x for x in df.columns if x != feature])\n","                if len(test_df.index) != 0:\n","                    pipe = make_pipeline(StandardScaler(), model)\n","                    y = train_df[feature].astype('int')\n","                    X_train = train_df.drop(feature, axis=1)\n","                    test_df.drop(feature, axis=1, inplace=True)\n","                    try:\n","                        model = pipe.fit(X_train, y)\n","                    except:\n","                        y = np.log(train_df[feature].astype('int'))\n","                        model = pipe.fit(X_train, y)\n","                    if (y == np.log(train_df[feature].astype('int'))).all():\n","                        pred = model.predict(test_df)\n","                    else:\n","                        pred = np.exp(model.predict(test_df))\n","                    test_df[feature]= pred\n","                    if (df[feature].fillna(-9999) % 1  == 0).all():\n","                        test_df[feature] = test_df[feature].round()\n","                        test_df[feature] = test_df[feature].astype('Int64')\n","                        df[feature].update(test_df[feature])\n","                    else:\n","                        df[feature].update(test_df[feature])\n","            except:\n","                pass\n","        for feature in df.columns:\n","            try:\n","                mappings_inv = {v: k for k, v in mapping[feature].items()}\n","                df[feature] = df[feature].map(mappings_inv)\n","            except:\n","                pass\n","        return df\n","    def _delete(self, df, type):\n","        if type == 'num':\n","            cols_num = df.select_dtypes(include=np.number).columns\n","            for feature in df.columns:\n","                if feature in cols_num:\n","                    df = df.dropna(subset=[feature])\n","        else:\n","            for feature in df.columns:\n","                if feature not in cols_num:\n","                    df = df.dropna(subset=[feature])\n","        return df\n","\n","\n","from scipy.stats import zscore\n","class Outliers:\n","    def __init__(self, method=None):\n","        self.method = method\n","    def fit(self, X, y=None):\n","        return self\n","    def transform(self, X):\n","        return X\n","    def handle(self, df):\n","        if self.method:\n","            self.count_outliers = 0\n","            if self.method == 'zscore':\n","                df, self.count_outliers = self._zscore_outliers(df)\n","            elif self.method == 'iqr':\n","                df, self.count_outliers = self._iqr_outliers(df)\n","            elif self.method == 'manual':\n","                df, self.count_outliers = self._manual_outliers(df)\n","            else:\n","                pass\n","        return df\n","    def _zscore_outliers(self, df):\n","        outlier_count = 0\n","        cols_num = df.select_dtypes(include=np.number).columns\n","        for feature in cols_num:\n","            if df[feature].dtype != 'object':\n","                z_scores = zscore(df[feature])\n","                abs_z_scores = np.abs(z_scores)\n","                outliers = (abs_z_scores > self.threshold).sum()\n","                outlier_count += outliers\n","                df = df[(abs_z_scores < self.threshold).all(axis=1)]\n","        return df, outlier_count\n","    def _iqr_outliers(self, df):\n","        outlier_count = 0\n","        cols_num = df.select_dtypes(include=np.number).columns\n","        for feature in cols_num:\n","            if df[feature].dtype != 'object':\n","                q1 = df[feature].quantile(0.25)\n","                q3 = df[feature].quantile(0.75)\n","                iqr = q3 - q1\n","                lower_bound = q1 - (self.threshold * iqr)\n","                upper_bound = q3 + (self.threshold * iqr)\n","                outliers = ((df[feature] < lower_bound) | (df[feature] > upper_bound)).sum()\n","                outlier_count += outliers\n","                df = df[(df[feature] >= lower_bound) & (df[feature] <= upper_bound)]\n","        return df, outlier_count\n","    def _manual_outliers(self, df):\n","        outlier_count = 0\n","        for feature in self.manual_dict:\n","            if feature in df.columns:\n","                outliers = df[df[feature].isin(self.manual_dict[feature])]\n","                outlier_count += len(outliers)\n","                df = df[~df[feature].isin(self.manual_dict[feature])]\n","        return df, outlier_count\n","\n","\n","class Adjust:\n","    def __init__(self, scaler=None, extract_datetime=False, round_values=False):\n","        self.scaler = scaler\n","        self.extract_datetime = extract_datetime\n","        self.round_values = round_values\n","    def fit(self, X, y=None):\n","        return self\n","    def transform(self, X):\n","        return X\n","    def handle(self, df):\n","        if self.scaler == 'minmax':\n","            scaler = preprocessing.MinMaxScaler()\n","        elif self.scaler == 'standard':\n","            scaler = preprocessing.StandardScaler()\n","        elif self.scaler == 'robust':\n","            scaler = preprocessing.RobustScaler()\n","        elif self.scaler == 'maxabs':\n","            scaler = preprocessing.MaxAbsScaler()\n","        elif self.scaler == 'quantile':\n","            scaler = preprocessing.QuantileTransformer()\n","        elif self.scaler == 'power':\n","            scaler = preprocessing.PowerTransformer()\n","        if self.extract_datetime:\n","            df = self._convert_datetime(df)\n","        if self.round_values:\n","            df = self._round_values(df)\n","        df[df.columns] = scaler.fit_transform(df[df.columns])\n","        return df\n","    def _convert_datetime(self, df):\n","        cols = set(df.columns) ^ set(df.select_dtypes(include=np.number).columns)\n","        for feature in cols:\n","            try:\n","                df[feature] = pd.to_datetime(df[feature], infer_datetime_format=True)\n","                try:\n","                    df['Day'] = pd.to_datetime(df[feature]).dt.day\n","                    if self.extract_datetime in ['auto', 'M','Y','h','m','s']:\n","                        df['Month'] = pd.to_datetime(df[feature]).dt.month\n","                        if self.extract_datetime in ['auto', 'Y','h','m','s']:\n","                            df['Year'] = pd.to_datetime(df[feature]).dt.year\n","                            if self.extract_datetime in ['auto', 'h','m','s']:\n","                                df['Hour'] = pd.to_datetime(df[feature]).dt.hour\n","                                if self.extract_datetime in ['auto', 'm','s']:\n","                                    df['Minute'] = pd.to_datetime(df[feature]).dt.minute\n","                                    if self.extract_datetime in ['auto', 's']:\n","                                        df['Sec'] = pd.to_datetime(df[feature]).dt.second\n","                except:\n","                    pass\n","            except:\n","                pass\n","        return df\n","    def _round_values(self, df):\n","        cols_num = df.select_dtypes(include=np.number).columns\n","        for feature in cols_num:\n","            if (df[feature].fillna(-9999) % 1  == 0).all():\n","                try:\n","                    df[feature] = df[feature].astype('Int64')\n","                except:\n","                    pass\n","            else:\n","                try:\n","                    df[feature] = df[feature].astype(float)\n","                    dec = None\n","                    for value in df[feature]:\n","                        try:\n","                            if dec is None:\n","                                dec = str(value)[::-1].find('.')\n","                            else:\n","                                if str(value)[::-1].find('.') > dec:\n","                                    dec = str(value)[::-1].find('.')\n","                        except:\n","                            pass\n","                    df[feature] = df[feature].round(decimals=dec)\n","                except:\n","                    pass\n","        return df\n","\n","\n","class EncodeCateg:\n","    def __init__(self, encode_categ=None):\n","        self.encode_categ = encode_categ\n","    def fit(self, X, y=None):\n","        return self\n","    def transform(self, X):\n","        return X\n","    def handle(self, df):\n","        if self.encode_categ:\n","            if not isinstance(self.encode_categ, list):\n","                self.encode_categ = ['auto']\n","            cols_categ = set(df.columns) ^ set(df.select_dtypes(include=pd.np.number).columns)\n","            if len(self.encode_categ) == 1:\n","                target_cols = cols_categ\n","            else:\n","                target_cols = self.encode_categ[1]\n","            for feature in target_cols:\n","                if feature in cols_categ:\n","                    feature = feature\n","                else:\n","                    feature = df.columns[feature]\n","                try:\n","                    pd.to_datetime(df[feature])\n","                except:\n","                    try:\n","                        if self.encode_categ[0] == 'auto':\n","                            if df[feature].nunique() <=10:\n","                                df = self._to_onehot(df, feature)\n","                            elif df[feature].nunique() <=20:\n","                                df = self._to_label(df, feature)\n","                        elif self.encode_categ[0] == 'onehot':\n","                            df = self._to_onehot(df, feature)\n","                        elif self.encode_categ[0] == 'label':\n","                            df = self._to_label(df, feature)\n","                    except:\n","                        pass\n","        return df\n","    def _to_onehot(self, df, feature, limit=10):\n","        one_hot = pd.get_dummies(df[feature], prefix=feature)\n","        if one_hot.shape[1] > limit:\n","            print('ONEHOT encoding for feature \"{}\" creates {} new features. Consider LABEL encoding instead.'.format(feature, one_hot.shape[1]))\n","        df = df.join(one_hot)\n","        return df\n","    def _to_label(self, df, feature):\n","        le = LabelEncoder()\n","        df[feature + '_lab'] = le.fit_transform(df[feature].values)\n","        mapping = dict(zip(le.classes_, range(len(le.classes_))))\n","        for key in mapping:\n","            try:\n","                if pd.np.isnan(key):\n","                    replace = {mapping[key] : key }\n","                    df[feature].replace(replace, inplace=True)\n","            except:\n","                pass\n","        return df"],"metadata":{"id":"hm7LXl1iaP6j"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["dataset = pd.read_csv('dp_data1.csv')\n","dataset.info()"],"metadata":{"id":"TGU40qkbaCCD","executionInfo":{"status":"ok","timestamp":1709539690441,"user_tz":-330,"elapsed":13,"user":{"displayName":"Chinmay Kanawade","userId":"02462673596510628563"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"61c6cc3b-cd9b-49fd-f729-e7cd11a874c0"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["<class 'pandas.core.frame.DataFrame'>\n","RangeIndex: 1000 entries, 0 to 999\n","Data columns (total 25 columns):\n"," #   Column      Non-Null Count  Dtype  \n","---  ------      --------------  -----  \n"," 0   Feature_1   1000 non-null   float64\n"," 1   Feature_2   1000 non-null   float64\n"," 2   Feature_3   1000 non-null   float64\n"," 3   Feature_4   1000 non-null   int64  \n"," 4   Feature_5   1000 non-null   int64  \n"," 5   Feature_6   1000 non-null   object \n"," 6   Feature_7   1000 non-null   int64  \n"," 7   Feature_8   1000 non-null   float64\n"," 8   Feature_9   1000 non-null   float64\n"," 9   Feature_10  1000 non-null   float64\n"," 10  Feature_11  1000 non-null   int64  \n"," 11  Feature_12  1000 non-null   float64\n"," 12  Feature_13  1000 non-null   float64\n"," 13  Feature_14  1000 non-null   float64\n"," 14  Feature_15  1000 non-null   int64  \n"," 15  Feature_16  1000 non-null   float64\n"," 16  Feature_17  782 non-null    float64\n"," 17  Feature_18  1000 non-null   float64\n"," 18  Feature_19  746 non-null    object \n"," 19  Feature_20  1000 non-null   float64\n"," 20  Feature_21  1000 non-null   float64\n"," 21  Feature_22  674 non-null    float64\n"," 22  Feature_23  1000 non-null   float64\n"," 23  Feature_24  1000 non-null   float64\n"," 24  Feature_25  1000 non-null   object \n","dtypes: float64(17), int64(5), object(3)\n","memory usage: 195.4+ KB\n"]}]},{"cell_type":"code","source":["print(\"Column indexes:\")\n","for i, column in enumerate(dataset.columns):\n","    print(f\"{i} : {column}\")\n","\n","target_index = int(input(\"Enter the index of the target variable: \"))\n","target_variable = dataset.columns[target_index]"],"metadata":{"id":"0XgDaQP5lV4P","executionInfo":{"status":"ok","timestamp":1709539705628,"user_tz":-330,"elapsed":4173,"user":{"displayName":"Chinmay Kanawade","userId":"02462673596510628563"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"9d011b2d-b09b-45bd-e5e5-26566a0b4529"},"execution_count":null,"outputs":[{"name":"stdout","output_type":"stream","text":["Column indexes:\n","0 : Feature_1\n","1 : Feature_2\n","2 : Feature_3\n","3 : Feature_4\n","4 : Feature_5\n","5 : Feature_6\n","6 : Feature_7\n","7 : Feature_8\n","8 : Feature_9\n","9 : Feature_10\n","10 : Feature_11\n","11 : Feature_12\n","12 : Feature_13\n","13 : Feature_14\n","14 : Feature_15\n","15 : Feature_16\n","16 : Feature_17\n","17 : Feature_18\n","18 : Feature_19\n","19 : Feature_20\n","20 : Feature_21\n","21 : Feature_22\n","22 : Feature_23\n","23 : Feature_24\n","24 : Feature_25\n","Enter the index of the target variable: 20\n"]}]},{"cell_type":"code","source":["from sklearn.pipeline import Pipeline\n","preprocessing__pipeline = Pipeline([\n","    ('missing_values', MissingValues(missing_num='knn', missing_categ='logreg')),\n","    ('outliers', Outliers(method='zscore')),\n","    ('adjust', Adjust(scaler='standard', extract_datetime=True, round_values=True)),\n","    ('encode_categ', EncodeCateg(encode_categ=['auto'])),\n","    ('duplicates', Duplicates())\n","])\n","\n","cleaned_dataset = preprocessing_pipeline(dataset, target_variable)\n","cleaned_dataset.info()"],"metadata":{"id":"HuqSqnh5aQG0","executionInfo":{"status":"ok","timestamp":1709539711125,"user_tz":-330,"elapsed":513,"user":{"displayName":"Chinmay Kanawade","userId":"02462673596510628563"}},"colab":{"base_uri":"https://localhost:8080/"},"outputId":"8a7918ac-d3d3-4c0f-ecaf-0916724e8f85"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stdout","text":["<class 'pandas.core.frame.DataFrame'>\n","RangeIndex: 1000 entries, 0 to 999\n","Data columns (total 21 columns):\n"," #   Column      Non-Null Count  Dtype  \n","---  ------      --------------  -----  \n"," 0   PC1         1000 non-null   float64\n"," 1   PC2         1000 non-null   float64\n"," 2   PC3         1000 non-null   float64\n"," 3   PC4         1000 non-null   float64\n"," 4   PC5         1000 non-null   float64\n"," 5   PC6         1000 non-null   float64\n"," 6   PC7         1000 non-null   float64\n"," 7   PC8         1000 non-null   float64\n"," 8   PC9         1000 non-null   float64\n"," 9   PC10        1000 non-null   float64\n"," 10  PC11        1000 non-null   float64\n"," 11  PC12        1000 non-null   float64\n"," 12  PC13        1000 non-null   float64\n"," 13  PC14        1000 non-null   float64\n"," 14  PC15        1000 non-null   float64\n"," 15  PC16        1000 non-null   float64\n"," 16  PC17        1000 non-null   float64\n"," 17  PC18        1000 non-null   float64\n"," 18  PC19        1000 non-null   float64\n"," 19  PC20        1000 non-null   float64\n"," 20  Feature_21  1000 non-null   float64\n","dtypes: float64(21)\n","memory usage: 164.2 KB\n"]}]},{"cell_type":"markdown","source":["<h1>MODEL SELECTION</h1>"],"metadata":{"id":"ZvB0k7AhkPBO"}},{"cell_type":"code","source":["from sklearn.model_selection import train_test_split, RandomizedSearchCV\n","from sklearn.metrics import accuracy_score, mean_squared_error\n","from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier\n","from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier\n","from scipy.stats import randint, uniform\n","\n","target_dtype = dataset[target_variable].dtype\n","\n","def split_data(dataset, target_variable):\n","    X = dataset.drop(columns=[target_variable])\n","    y = dataset[target_variable]\n","    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n","    return X_train, X_test, y_train, y_test\n","\n","def tune_hyperparameters(model, param_distributions, X_train, y_train):\n","    search = RandomizedSearchCV(estimator=model, param_distributions=param_distributions, n_iter=10, scoring='accuracy', cv=5, random_state=42)\n","    search.fit(X_train, y_train)\n","    return search.best_estimator_\n","\n","def select_models(target_dtype):\n","    regression_models = [LinearRegression(), RandomForestRegressor()]\n","    classification_models = [LogisticRegression(), DecisionTreeClassifier(), RandomForestClassifier()]\n","\n","    if target_dtype in [np.float64, np.int64]:\n","        return regression_models\n","    elif target_dtype == object:\n","        return classification_models\n","    else:\n","        raise ValueError(\"Unsupported target variable type. Please ensure the target variable is numeric or categorical.\")\n","\n","def evaluate_model(model, X_test, y_test, problem_type):\n","    y_pred = model.predict(X_test)\n","    if problem_type == 'classification':\n","        return accuracy_score(y_test, y_pred)\n","    elif problem_type == 'regression':\n","        return mean_squared_error(y_test, y_pred)\n","\n","X_train, X_test, y_train, y_test = split_data(cleaned_dataset, target_variable)\n","\n","models = select_models(dataset[target_variable].dtype)\n","\n","best_model = None\n","best_score = 0\n","\n","param_grid = {\n","    'LinearRegression': {},\n","    'DecisionTreeRegressor': {\n","        'max_depth': randint(1, 20),\n","        'min_samples_split': randint(2, 20),\n","        'min_samples_leaf': randint(1, 20)\n","    },\n","    'RandomForestRegressor': {\n","        'n_estimators': randint(10, 100),\n","        'max_depth': randint(1, 20),\n","        'min_samples_split': randint(2, 20),\n","        'min_samples_leaf': randint(1, 20),\n","        'max_features': randint(2, 10)\n","    },\n","    'LogisticRegression': {\n","        'C': uniform(0, 10),\n","        'penalty': ['l1', 'l2']\n","    },\n","    'DecisionTreeClassifier': {\n","        'max_depth': randint(1, 20),\n","        'min_samples_split': randint(2, 20),\n","        'min_samples_leaf': randint(1, 20)\n","    },\n","    'RandomForestClassifier': {\n","        'n_estimators': randint(10, 100),\n","        'max_depth': randint(1, 20),\n","        'min_samples_split': randint(2, 20),\n","        'min_samples_leaf': randint(1, 20),\n","        'max_features': uniform(0, 1)\n","    }\n","}\n","\n","for model in models:\n","    model.fit(X_train, y_train)\n","    score = evaluate_model(model, X_test, y_test, 'regression' if target_dtype in [np.float64, np.int64] else 'classification')\n","    if (target_dtype in [np.float64, np.int64] and score > best_score) or (target_dtype == object and score < best_score):\n","        best_score = score\n","        best_model = model\n","\n","    if model.__class__.__name__ in param_grid:\n","        best_model = tune_hyperparameters(model, param_grid[model.__class__.__name__], X_train, y_train)\n","    print(f'Model: {model} -- score: {score}')\n","\n","best_model.fit(cleaned_dataset.drop(columns=[target_variable]), cleaned_dataset[target_variable])\n"],"metadata":{"id":"P7u78D0DXJSZ","executionInfo":{"status":"ok","timestamp":1709540570287,"user_tz":-330,"elapsed":8873,"user":{"displayName":"Chinmay Kanawade","userId":"02462673596510628563"}},"colab":{"base_uri":"https://localhost:8080/","height":1000},"outputId":"61533456-46e7-4df0-de31-9de8b9098fb3"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 1 is smaller than n_iter=10. Running 1 iterations. For exhaustive searches, use GridSearchCV.\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [nan]\n","  warnings.warn(\n"]},{"output_type":"stream","name":"stdout","text":["Model: LinearRegression() -- score: 0.3601819237281984\n"]},{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:778: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: \n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py\", line 767, in _score\n","    scores = scorer(estimator, X_test, y_test)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 234, in __call__\n","    return self._score(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py\", line 282, in _score\n","    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py\", line 192, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 221, in accuracy_score\n","    y_type, y_true, y_pred = _check_targets(y_true, y_pred)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py\", line 106, in _check_targets\n","    raise ValueError(\"{0} is not supported\".format(y_type))\n","ValueError: continuous is not supported\n","\n","  warnings.warn(\n","/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:952: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan nan nan nan nan nan nan]\n","  warnings.warn(\n"]},{"output_type":"stream","name":"stdout","text":["Model: RandomForestRegressor() -- score: 0.3641750182046754\n"]},{"output_type":"execute_result","data":{"text/plain":["RandomForestRegressor(max_depth=7, max_features=5, min_samples_leaf=15,\n","                      min_samples_split=12, n_estimators=81)"],"text/html":["<style>#sk-container-id-2 {color: black;background-color: white;}#sk-container-id-2 pre{padding: 0;}#sk-container-id-2 div.sk-toggleable {background-color: white;}#sk-container-id-2 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-2 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-2 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-2 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-2 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-2 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-2 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-2 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-2 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-2 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-2 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-2 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-2 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-2 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-2 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-2 div.sk-item {position: relative;z-index: 1;}#sk-container-id-2 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-2 div.sk-item::before, #sk-container-id-2 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-2 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-2 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-2 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-2 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-2 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-2 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-2 div.sk-label-container {text-align: center;}#sk-container-id-2 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-2 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-2\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestRegressor(max_depth=7, max_features=5, min_samples_leaf=15,\n","                      min_samples_split=12, n_estimators=81)</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-2\" type=\"checkbox\" checked><label for=\"sk-estimator-id-2\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">RandomForestRegressor</label><div class=\"sk-toggleable__content\"><pre>RandomForestRegressor(max_depth=7, max_features=5, min_samples_leaf=15,\n","                      min_samples_split=12, n_estimators=81)</pre></div></div></div></div></div>"]},"metadata":{},"execution_count":16}]},{"cell_type":"code","source":["#Bayesian Network\n","from skopt import BayesSearchCV\n","from skopt.space import Real, Integer, Categorical\n","from sklearn.neural_network import MLPClassifier, MLPRegressor\n","from sklearn.metrics import accuracy_score, mean_squared_error\n","from sklearn.model_selection import train_test_split\n","\n","def objective_function(params):\n","    hidden_layer_sizes = params['hidden_layer_sizes']\n","    activation = params['activation']\n","    solver = params['solver']\n","    alpha = params['alpha']\n","\n","    model = MLPClassifier(hidden_layer_sizes=hidden_layer_sizes,\n","                          activation=activation,\n","                          solver=solver,\n","                          alpha=alpha,\n","                          random_state=42)\n","\n","    model.fit(X_train, y_train)\n","\n","    if problem_type == 'classification':\n","        y_pred = model.predict(X_val)\n","        score = accuracy_score(y_val, y_pred)\n","    elif problem_type == 'regression':\n","        y_pred = model.predict(X_val)\n","        score = -mean_squared_error(y_val, y_pred)\n","\n","    return score\n","\n","search_space = {\n","    'hidden_layer_sizes': Integer(50, 200, prior='uniform'),\n","    'activation': Categorical(['relu', 'tanh']),\n","    'solver': Categorical(['adam', 'sgd']),\n","    'alpha': Real(1e-5, 1e-2, prior='log-uniform')\n","}\n","\n","X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)\n","\n","bo = BayesSearchCV(estimator=None, search_spaces=[search_space], n_iter=50, cv=5, scoring=None)\n","\n","bo.fit(X_train, y_train)\n","\n","best_params = bo.best_params_\n","print(\"Best Hyperparameters:\", best_params)\n","\n","final_model = MLPClassifier(**best_params, random_state=42)\n","final_model.fit(X_train, y_train)"],"metadata":{"id":"nqVTJ9icm7Vx"},"execution_count":null,"outputs":[]}]}